### ISSUE TITLE
Error when using taniwha with AE2

### ISSUE THREAD

**Issue by ianmeinert** [Lemonszz/taniwha#1]
### Background
I was troubleshooting why I couldn't get the AE2 spatial cells to work in the IO Port when their Discord community recommended I run the `/ae2 spatial` command. When I did, it threw an error. I scrubbed the log and found these entries:

### Pack
I am using the AOF 7 Fabric modpack, version 0.6.3.

### ISSUES
The issues prevent full implementation of the AE2 modpack.

1. WARN when pressing a button on the IO Port to activate a redstone pulse:

```[12:54:31] [Server thread/WARN]: Exception: 
java.lang.ClassCastException: class party.lemons.taniwha.level.LevelDataManager cannot be cast to class appeng.spatial.SpatialStorageWorldData (party.lemons.taniwha.level.LevelDataManager and appeng.spatial.SpatialStorageWorldData are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)
	at appeng.spatial.SpatialStoragePlotManager.getWorldData(SpatialStoragePlotManager.java:59) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.spatial.SpatialStoragePlotManager.allocatePlot(SpatialStoragePlotManager.java:74) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.items.storage.SpatialStorageCellItem.doSpatialTransition(SpatialStorageCellItem.java:142) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.blockentity.spatial.SpatialIOPortBlockEntity.lambda$transition$1(SpatialIOPortBlockEntity.java:172) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.api.networking.IManagedGridNode.ifPresent(IManagedGridNode.java:102) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.blockentity.spatial.SpatialIOPortBlockEntity.transition(SpatialIOPortBlockEntity.java:158) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.blockentity.spatial.SpatialIOPortBlockEntity.lambda$new$0(SpatialIOPortBlockEntity.java:52) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.hooks.ticking.TickHandler.processQueue(TickHandler.java:403) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:293) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.hooks.ticking.TickHandler.lambda$init$1(TickHandler.java:95) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-21c1963f26916f23.jar:?]
	at net.minecraft.server.MinecraftServer.handler$eba002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7862) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

2. ERROR when using the `/ae2 spatial` command:

```[12:55:14] [Server thread/ERROR]: Command exception: /ae2 spatial
java.lang.ClassCastException: class party.lemons.taniwha.level.LevelDataManager cannot be cast to class appeng.spatial.SpatialStorageWorldData (party.lemons.taniwha.level.LevelDataManager and appeng.spatial.SpatialStorageWorldData are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)
	at appeng.spatial.SpatialStoragePlotManager.getWorldData(SpatialStoragePlotManager.java:59) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.spatial.SpatialStoragePlotManager.getPlots(SpatialStoragePlotManager.java:91) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.server.subcommands.SpatialStorageCommand.call(SpatialStorageCommand.java:261) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at appeng.server.AECommand.lambda$add$1(AECommand.java:53) ~[appliedenergistics2-fabric-15.0.13.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
	at net.minecraft.class_2170.redirect$zpn000$architectury$performCommand(class_2170.java:1045) ~[client-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_45010(class_3244.java:1341) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1321) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### Steps to reproduce
1. Build out a a network as shown [here](https://imgur.com/gallery/BbDDuw8).

2. Activate the redstone signal. The 2x2x2 block of logs should disappear into the spatial cell in the IO Port

**Comment by Lemonszz** [comment]
This should already be fixed with the latest version of Biome Makeover/Taniwha. 

If you're on Biome Makeover 1.11.2+ and this still happens let me know!

Thanks

**Comment by ianmeinert** [comment]
It looks like the next major release of AOF 7 (v1.0.0) updated to biomemakeover-FABRIC-1.20.1-1.11.4.jar.

Thanks. Its confirmed that it works now.
